version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077" # Spark master port
      - "8080:8080" # Web UI port
    volumes:
      - ./data:/tmp/data # Mount the local ./data directory into /tmp/data inside the container

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081" # Web UI port for worker
    volumes:
      - ./data:/tmp/data # Mount the same ./data directory

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081" # Web UI port for worker
    volumes:
      - ./data:/tmp/data # Mount the same ./data directory
